############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
# Backend build


# LABEL maintainer=""
# LABEL version="1.0.0"
# LABEL description="This is the backend image for the app."
# LABEL org.opencontainers.image.description="This is the backend image for the app."